### ISSUE TITLE
3.65 - 3.68 support

### ISSUE THREAD

**Issue by Exeedy** [Rinnegatamante/Touch-Remap#1]
Great work thank you.. love all of your modules <3

Hope you could add 3.65 support because without this plugin it is impossible to play many games with remoteplay. Would it be possible to swap L1 with L2 and R1 with R2 too?

Thank you Keep up the good work <3

**Comment by CapCap67** [comment]
Yep also need a compatibility with 3.68 👍 ;D

**Comment by Rinnegatamante** [comment]
TouchRemap doesn't worth with remote play, no matter the fw version.
